#!/bin/bash

set -euo pipefail
. /.functions

#
# Init all the SSL-related stuff
#
init_ssl

#
# Add the requisite CATALINA_OPTS carrying certificate passwords (not the cleanest way, but
# Alfresco isn't smart enough to do better)
#
set_or_default CATALINA_OPTS
SSL_OPTS=(
	-Dencryption.ssl.keystore.location="${JAVA_KEYSTORE}"
	-Dencryption.ssl.keystore.type="${JAVA_KEYSTORE_TYPE}"

	-Dssl-keystore.password="${JAVA_KEYSTORE_PASSWORD}"
	-Dssl-keystore.aliases="${JAVA_KEY_ALIAS}"
	"-Dssl-keystore.${JAVA_KEY_ALIAS}.password=${JAVA_KEY_PASSWORD}"

	-Dencryption.ssl.truststore.location="${JAVA_TRUSTSTORE}"
	-Dencryption.ssl.truststore.type="${JAVA_TRUSTSTORE_TYPE}"
)
CATALINA_OPTS+=" ${SSL_OPTS[@]}"
export CATALINA_OPTS
unset SSL_OPTS

#
# Ignore any failures here
#
/usr/local/tomcat/shared/classes/alfresco/substituter.sh || true

#
# Start Tomcat!
#
execute "${TOMCAT_DIR}/bin/catalina.sh" run
